fix: moved Checkout directory exists to after downloan build

diff --git a/.github/workflows/azure-static-web-apps-blue-field-0f8b9f710.yml b/.github/workflows/azure-static-web-apps-blue-field-0f8b9f710.yml
--- a/.github/workflows/azure-static-web-apps-blue-field-0f8b9f710.yml
+++ b/.github/workflows/azure-static-web-apps-blue-field-0f8b9f710.yml
@@ -124,12 +124,7 @@ jobs:
       # - name: Build static site
       #   run: pnpm build
 
-      - name: Check out directory exists
-        run: |
-          if [ ! -d "out" ]; then
-            echo "Build output directory 'out/' not found!"
-            exit 1
-          fi
+      
 
       # - name: Upload static frontend
       #   uses: actions/upload-artifact@v4
@@ -143,6 +138,13 @@ jobs:
           name: nextjs-build
           path: out/
 
+      - name: Check out directory exists
+        run: |
+          if [ ! -d "out" ]; then
+            echo "Build output directory 'out/' not found!"
+            exit 1
+          fi
+          
       - uses: Azure/static-web-apps-deploy@v1
         with:
           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_FIELD_0F8B9F710 }}
